#default properties
server:
  port: 8081

spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/storage
      username: postgres
      password: somePassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update

logging:
  config: classpath:logback-spring.xml
  file:
    name: logs/auth.log